//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2GetDataTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplyInfo
    {
        public int ID { get; set; }
        public string ProcessID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string Applicant { get; set; }
        public string Department { get; set; }
        public double InvoiceValue { get; set; }
        public double PayMoney { get; set; }
        public string PayModel { get; set; }
        public string PayWho { get; set; }
        public string BankAccount { get; set; }
        public string ApplyStatus { get; set; }
        public string PayType { get; set; }
    }
}
