//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ng2GetDataTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTab
    {
        public string id { get; set; }
        public string desc { get; set; }
        public bool completed { get; set; }
        public string ProcessID { get; set; }
        public string ProcessName { get; set; }
    }
}
